### ISSUE TITLE
Reset form to default state

### ISSUE THREAD

**Issue by Failcookie** [cretueusebiu/vform#15]
Has anyone figured out the best way to reset the form to its original state? Right now, I am popping an edit form in a modal dialog box and I am trying to clear it out on close.

**Comment by cretueusebiu** [comment]
Use [form.reset()](https://github.com/cretueusebiu/vform#api).

**Comment by Failcookie** [comment]
Holy crap! I can't believe I missed that one. Thank you for that

**Comment by maganius** [comment]
Sorry to re-open this issue but my problem has same title.

I have a similar problem.
with form.reset() it clear all data from form object but how I can reset it to initial data form?
example:

```
data: () => ({
     form: new Form({remitente: this.remitente, lotes: []}),
})
```
I need re-fill the remitente object after form.reset()? because 'remitente' is static and needed sent to form always.

I think set static information to form would be useful.

I see form.ignore array is present, how I can add new columns?

**Comment by cretueusebiu** [comment]
@maganius The `form.reset()` method works fine for simple forms, but when you have nested objects (maybe with references) it's better to use a function to create and reset the form:

```javascript
data: () => ({
  form: new Form({
     remitente: [], 
     lotes: []
  }),
}),

created () {
  this.resetForm()
},

methods: {
  async save () {
    await this.form.post('/api/resource')

    this.resetForm() 
  },

  resetForm () {
    this.form.remitente = this.remitente
    // and so on... 
 }
}
```

**Comment by maganius** [comment]
thanks you @cretueusebiu, this vform is awesome!
